<!DOCTYPE HTML>
<html>
<head>
  <base href="/admin/" />
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <title><?= $titulek ?></title>
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="Jan Baxa - jencekk@email.cz" />
  <link rel="stylesheet" type="text/css" href="slova-v-oborech.css" />
  <script type='text/javascript' src="jquery-1.11.2.min.js"></script>
  <script type='text/javascript' src='oznac_sloupec.js'></script>
</head>
<body>
	<?php $this->kontroler->vypisPohled();?> 
</body>
</html>