<!-- Podstránka pro zobrazení všech klíčových slov a jejich vazeb k jednotlivým oborům -->
<div class='csstransforms'>
		<!-- Výpis typů studia -->
		<?php
			foreach ($typy as $typ)	{
		?>
		<div class='tabulka'>Typ studia: <?= $typ["nazev"]?></div>
			<table class="table table-header-rotated">
			<!-- Hlavička tabulky - studijní obory v daném typu studia -->
				<thead>
					<tr>
						<th></th>
						<?php
							if ($typ["obory"])	{
								foreach ($typ["obory"] as $obor)	{
						?>
							<th class="rotate"><div><span><?= $obor["nazev"]?> (<?= $obor["forma"][0]?>)</span></div></th>
						<?php
								}
							}
						?>
					</tr>
				</thead>
				<tbody>
					<!-- Tělo tabulky - klíčová slova a jejich priority vazeb k oborům -->
					<?php
						if ($typ["obory"])	{
							foreach ($typ["slova"] as $slovo)	{
					?>
						<tr>
							<th class="row-header"><?= $slovo["nazev"]?></th>
							<?php
								$i = 0;
								foreach ($slovo["priority"] as $priorita)	{
									$tridaBarvy = "";
									switch ($priorita["hodnota"])	{
										case "0.5": $tridaBarvy = "red"; break;
										case "0.75": $tridaBarvy = "orange"; break;
										case "1": $tridaBarvy = "green"; break;
										default: $tridaBarvy = "grey"; break;
									}
							?>
								<td class='sloupec_<?= $i?>' title='<?= $priorita["obor"]?> (<?= $priorita["forma"][0]?>)'><span class='<?= $tridaBarvy?>'><?= $priorita["hodnota"];?></span></td>
							<?php
									$i++;
								}
							?>
						</tr>
					<?php
							}
						}
					?>
				</tbody>
			</table>
		<?php
			}
		?>
</div>